# This file shouldn't be necessary once
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysqlinstances.common.crossplane.io
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
  - apiGroups:
      - common.crossplane.io
    resources:
      - mysqlinstances
      - mysqlinstances/status
      - mysqlinstanceclaims
      - mysqlinstanceclaims/status
    verbs:
      - "*"
