---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: CompositeResourceDefinition
metadata:
  name: mysqlinstances.common.crossplane.io
spec:
  claimNames:
    kind: MySQLInstanceClaim
    listKind: MySQLInstanceClaimList
    plural: mysqlinstanceclaims
    singular: mysqlinstanceclaim
  connectionSecretKeys:
    - username
    - password
    - endpoint
    - port
  crdSpecTemplate:
    group: common.crossplane.io
    version: v1alpha1
    names:
      categories:
        - crossplane
      kind: MySQLInstance
      listKind: MySQLInstanceList
      plural: mysqlinstances
      singular: mysqlinstance
    validation:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              version:
                description: Version specifies the desired MySQL engine version,
                  e.g. 5.7.
                enum:
                  - "5.6"
                  - "5.7"
                type: string
              storageGB:
                type: integer
              region:
                type: string
            required:
              - version
              - storageGB
